export const ICONS_MAP = {
  react: { name: 'React', icon: 'react' },
  vue: { name: 'Vue', icon: 'vue' },
  nodeJS: { name: 'Node.js', icon: 'node-js' },
  tailwindCSS: { name: 'Tailwind CSS', icon: 'tailwind-css' },
  typescript: { name: 'TypeScript', icon: 'typescript' },
  jest: { name: 'Jest', icon: 'jest' },
  cypress: { name: 'Cypress', icon: 'cypress' },
  sass: { name: 'Sass', icon: 'sass' },
  html: { name: 'HTML', icon: 'html' },
  css: { name: 'CSS', icon: 'css' },
  reactQuery: { name: 'React Query', icon: 'react-query' },
  redux: { name: 'Redux', icon: 'redux' },
  astro: { name: 'Astro', icon: 'astro' },
  webpack: { name: 'Webpack', icon: 'webpack' },
  swc: { name: 'SWC', icon: 'swc' },
  ionic: { name: 'Ionic', icon: 'ionic' },
  firebase: { name: 'Firebase', icon: 'firebase' },
  php: { name: 'PHP', icon: 'php' },
  laravel: { name: 'Laravel', icon: 'laravel' },
  docker: { name: 'Docker', icon: 'docker' },
  figma: { name: 'Figma', icon: 'figma' },
  angular: { name: 'Angular', icon: 'angular' },
  javascript: { name: 'Javascript', icon: 'javascript' },
  reactTestingLibrary: { name: 'RTL', icon: 'react-testing-library' },
  materialUI: { name: 'Material UI', icon: 'material-ui' }
}
